name: Packaging

on: [push]

jobs:
  packaging:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
      with:
        php_version: "7.4"
    - uses: actions/upload-artifact@v3
      with:
        name: contactform
        path: |
          vendor/
          *.php
          *.md
          !.*

  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
