name: Package

on: [push]

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6
      with:
        php_version: "7.4"
    - run: |
        zip contactform.zip vendor *.php
    - uses: actions/upload-artifact@v3
      with:
        name: contactform
        path: contactform.zip

  release:
    runs-on: ubuntu-latest
    needs: package

    steps:
    - uses: actions/download-artifact@v3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: contactform
        path: contactform.zip
    - run: |
        ls -alh contactform.zip
    - uses: actions/create-release@v1
      id: create_release
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false
    - uses: actions/upload-release-asset@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ./contactform.zip
        asset_name: contactform.zip
        asset_content_type: application/zip
