name: Test

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: php-actions/composer@v6
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3
